platform :ios, '7.0'
target 'QYLiveSDKDemo' do
    xcodeproj 'QYLiveSDKDemo/QYLiveSDKDemo.xcodeproj'
    pod 'AFNetworking', '~> 3.1.0'
    pod 'KSYGPULive_iOS', '~> 1.5.4'
    pod 'SDWebImage',   '~> 3.7.6'
    pod 'Masonry',      '~> 1.0.0'
    pod 'RongCloudIMLib', '~> 2.6.4'
    pod 'MJRefresh',  '~>3.1.0'
    pod 'pop', '~> 1.0'
    pod 'FMDB','~> 2.6.2'
    pod 'SSZipArchive','1.2'
end
